# Imported strong-bot module split. Keep protocol code in national_bot.py.
import bisect
import itertools
import math
import random

N_PLAYERS = 2
INITIAL_CHIPS = 20000
SMALL_BLIND = 50
BIG_BLIND = 100
TOTAL_HANDS = 70
HAND_COUNT_SCALE = TOTAL_HANDS / 50.0
LOCK_WIN_MARGIN = int(round(1500 * HAND_COUNT_SCALE))
ENDGAME_HANDS = math.ceil(12 * HAND_COUNT_SCALE)
ENDGAME_RAMP_HANDS = math.ceil(10 * HAND_COUNT_SCALE)
ANTI_LOCK_JAM_HANDS = math.ceil(3 * HAND_COUNT_SCALE)
ANTI_LOCK_FALLBACK_JAM_HANDS = math.ceil(4 * HAND_COUNT_SCALE)
ANTI_LOCK_AIR_HANDS = math.ceil(5 * HAND_COUNT_SCALE)
ANTI_LOCK_WEAK_SHOWDOWN_HANDS = math.ceil(6 * HAND_COUNT_SCALE)
ANTI_LOCK_PREFLOP_JAM_FLOOR = 0.50
ANTI_LOCK_PREFLOP_LAST_HAND_FLOOR = 0.40
ANTI_LOCK_POSTFLOP_JAM_FLOOR = 0.36

HAND_CLASS_SCORE = [0.08, 0.22, 0.40, 0.58, 0.69, 0.76, 0.84, 0.93, 0.98]
SIMULATIONS_BY_PUBLIC_COUNT = {
    0: 500,
    3: 700,
    4: 900,
    5: 0,
}
EXTRA_SIMULATIONS_BY_PUBLIC_COUNT = {
    0: 200,
    3: 220,
    4: 180,
}
