"""新平台 SQLite 存储层(与 TCP 通道的 store/ 隔离)。"""
from .db import DEFAULT_DB_PATH, Store
from .schema import (
    PROTO_JSON, PROTO_TCP,
    ROLE_ADMIN, ROLE_USER,
    STATUS_ABORTED, STATUS_COMPLETED, STATUS_PENDING, STATUS_RUNNING,
    TYPE_CHALLENGE, TYPE_EXHIBITION, TYPE_LADDER,
)

__all__ = [
    "Store", "DEFAULT_DB_PATH",
    "ROLE_USER", "ROLE_ADMIN",
    "PROTO_JSON", "PROTO_TCP",
    "STATUS_PENDING", "STATUS_RUNNING", "STATUS_COMPLETED", "STATUS_ABORTED",
    "TYPE_CHALLENGE", "TYPE_LADDER", "TYPE_EXHIBITION",
]
