# ══════════════════════════════════════════════════════════════════════════════
# claude_v27 — Central Constants
# ══════════════════════════════════════════════════════════════════════════════

# ── Table Structure ────────────────────────────────────────────────────────────
N_PLAYERS = 2
INITIAL_CHIPS = 20000
SMALL_BLIND = 50
BIG_BLIND = 100
TOTAL_HANDS = 70
LOCK_WIN_MARGIN = 1500

# ── Hand Strength Scoring ─────────────────────────────────────────────────────
# Indexed by hand_class (0=highcard .. 8=straight_flush)
HAND_CLASS_SCORE = [0.08, 0.22, 0.40, 0.58, 0.69, 0.76, 0.84, 0.93, 0.98]

# Made-hand metric: per-rank detail weight in evaluate_best contribution
MADE_RANK_DETAIL_WEIGHT = 0.008
MADE_STRENGTH_CAP = 0.995

# ── Board Texture Thresholds ──────────────────────────────────────────────────
# Flush pressure levels by max suit count on board
FLUSH_PRESSURE_QUADS = 1.0       # 4+ same suit
FLUSH_PRESSURE_TRIPS = 0.75      # 3 same suit
FLUSH_PRESSURE_PAIR = 0.35       # 2 same suit on 4+ card board

# Straight pressure levels by cards-in-window count
STRAIGHT_PRESSURE_FOUR = 1.0     # 4 of 5 window cards present
STRAIGHT_PRESSURE_THREE = 0.65   # 3 of 5 window cards present
STRAIGHT_PRESSURE_TWO = 0.28     # 2 close-together of 5 window cards present

# Wetness formula weights
WETNESS_FLUSH_WEIGHT = 0.18
WETNESS_STRAIGHT_WEIGHT = 0.22
WETNESS_HIGH_CARD_BONUS = 0.03   # when board high_card >= 12
WETNESS_TURN_UNPAIRED_BONUS = 0.04
WETNESS_PAIRED_PENALTY = 0.06

# Dynamic board triggers
DYNAMIC_FLUSH_THRESHOLD = 0.75
DYNAMIC_STRAIGHT_THRESHOLD = 0.65
DYNAMIC_WETNESS_THRESHOLD = 0.45

# Street texture classification thresholds
TEXTURE_MONOTONE_FLUSH = 0.75
TEXTURE_DRAW_HEAVY_FLUSH = 0.75
TEXTURE_DRAW_HEAVY_STRAIGHT = 0.65
TEXTURE_SEMI_FLUSH = 0.35
TEXTURE_SEMI_STRAIGHT = 0.28
TEXTURE_SEMI_WETNESS = 0.20

# ── Action Sizing ─────────────────────────────────────────────────────────────
# Bet size bucket boundaries (last_raise_pot_ratio)
BET_SIZE_SMALL_MAX = 0.30
BET_SIZE_MEDIUM_MAX = 0.75

# Base raise ratios by street (choose_raise)
RAISE_RATIO_PREFLOP_OPEN = 0.55
RAISE_RATIO_PREFLOP_FACING = 0.75
RAISE_RATIO_FLOP = 0.60
RAISE_RATIO_TURN = 0.70
RAISE_RATIO_RIVER = 0.85

# Preflop open sizing (BB multiples)
SB_OPEN_BASE_BB = 2.5
SB_OPEN_STRENGTH_SCALE = 2.2
SB_OPEN_STRENGTH_OFFSET = 0.58
BB_ISO_BASE_BB = 3.2
BB_ISO_STRENGTH_SCALE = 2.2
BB_ISO_STRENGTH_OFFSET = 0.60

# Anti-lock pressure sizing
ANTI_LOCK_PREFLOP_OPEN_RATIO = 2.20
ANTI_LOCK_PREFLOP_FACING_RATIO = 2.60
ANTI_LOCK_FLOP_RATIO = 1.15
ANTI_LOCK_TURN_RATIO = 1.35
ANTI_LOCK_RIVER_RATIO = 1.55
ANTI_LOCK_DYNAMIC_MULT = 1.08
ANTI_LOCK_BLOCKER_DRAW_MULT = 1.06
ANTI_LOCK_WEAK_SHOWDOWN_MULT = 1.12
ANTI_LOCK_JAM_STACK_RATIO = 0.72

# Overbet / bluff caps
RAISE_MAX_RATIO = 1.45
OVERBET_MAX_RATIO = 1.80
BLOCKER_BLUFF_CAP_BASE = 0.54
BLOCKER_BLUFF_WET_SCALE = 0.18
BLOCKER_BLUFF_STREET_SCALE = 0.08
PASSIVE_THIN_VALUE_MAX_RATIO = 0.40

# ── Opponent Model Priors ─────────────────────────────────────────────────────
# Default Bayesian priors (alpha = prior_mean * prior_weight)
PRIOR_VPIP = 0.58;           PRIOR_VPID_WEIGHT = 4.0
PRIOR_PFR = 0.28;            PRIOR_PFR_WEIGHT = 4.0
PRIOR_ALLIN_RATE = 0.05;     PRIOR_ALLIN_WEIGHT = 8.0
PRIOR_POSTFLOP_AGGR = 0.36;  PRIOR_POSTFLOP_AGGR_WEIGHT = 5.0
PRIOR_POSTFLOP_CHECK = 0.42; PRIOR_POSTFLOP_CHECK_WEIGHT = 5.0
PRIOR_FOLD_TO_RAISE = 0.44;  PRIOR_FTR_WEIGHT = 4.0
PRIOR_AGGRESSION = 0.30;     PRIOR_AGGRESSION_WEIGHT = 6.0
PRIOR_FLOP_AGGR = 0.36;      PRIOR_FLOP_AGGR_WEIGHT = 5.0
PRIOR_TURN_AGGR = 0.32;      PRIOR_TURN_AGGR_WEIGHT = 5.0
PRIOR_RIVER_AGGR = 0.28;     PRIOR_RIVER_AGGR_WEIGHT = 5.0
PRIOR_BARREL_FREQ = 0.45;    PRIOR_BARREL_WEIGHT = 4.0

# Default avg raise sizes (BB)
DEFAULT_AVG_RAISE_BB = 2.6
DEFAULT_FLOP_RAISE_BB = 3.0
DEFAULT_TURN_RAISE_BB = 4.5
DEFAULT_RIVER_RAISE_BB = 5.5

# Confidence curve: (total_actions - CONFIDENCE_OFFSET) / CONFIDENCE_SCALE
CONFIDENCE_OFFSET = 5
CONFIDENCE_SCALE = 35.0

# Passive opponent detection thresholds
PASSIVE_AGGR_MAX = 0.30
PASSIVE_VPIP_MIN = 0.50
PASSIVE_BARREL_MAX = 0.35
PASSIVE_CONFIDENCE_GATE = 0.25

# ── EQR (Equity Realization) ──────────────────────────────────────────────────
# Air hand (no made, no draw)
EQR_AIR_IP = 0.65
EQR_AIR_OOP = 0.55
EQR_AIR_MULTI_BARREL = -0.10
EQR_AIR_TURN = -0.05
EQR_AIR_RIVER = -0.12
EQR_AIR_FLOOR = 0.45
EQR_AIR_CEIL = 0.85

# Weak pair (middle/bottom/under/board pair)
EQR_WEAK_PAIR_IP = 0.82
EQR_WEAK_PAIR_OOP = 0.72
EQR_WEAK_PAIR_KICKER = -0.05
EQR_WEAK_PAIR_MULTI_BARREL = -0.06
EQR_WEAK_PAIR_RIVER = -0.06
EQR_WEAK_PAIR_FLOOR = 0.65
EQR_WEAK_PAIR_CEIL = 0.92

# Top pair weak kicker
EQR_TOP_PAIR_WEAK_IP = 0.88
EQR_TOP_PAIR_WEAK_OOP = 0.80
EQR_TOP_PAIR_WEAK_BARREL = -0.04
EQR_TOP_PAIR_WEAK_FLOOR = 0.75
EQR_TOP_PAIR_WEAK_CEIL = 0.95

# ── Fold Thresholds ───────────────────────────────────────────────────────────
# postflop_call_margin components
CALL_MARGIN_WEAK = 0.020
CALL_MARGIN_AIR = 0.028
CALL_MARGIN_AGGR_BASE = 0.008
CALL_MARGIN_SMALL_BET = 0.032
CALL_MARGIN_MEDIUM_BET = 0.010
CALL_MARGIN_LARGE_BET = 0.024
CALL_MARGIN_SMALL_REPEATED = 0.024
CALL_MARGIN_MEDIUM_REPEATED = 0.014
CALL_MARGIN_LATE_AIR = 0.020
CALL_MARGIN_RIVER_LARGE = 0.032
CALL_MARGIN_OOP = 0.008
CALL_MARGIN_DRY = -0.025
CALL_MARGIN_DRAW_HEAVY = 0.020
CALL_MARGIN_CLAMP_LOW = 0.0
CALL_MARGIN_CLAMP_HIGH = 0.08

# should_fold_postflop thresholds by street
FOLD_FLOP_WEAK = 0.20
FOLD_FLOP_MED = 0.22
FOLD_TURN_WEAK = 0.25
FOLD_TURN_MED = 0.28
FOLD_RIVER_WEAK = 0.35
FOLD_RIVER_MED = 0.40
FOLD_DRY_LATE_WEAK = 0.32
FOLD_DRY_RIVER_MED = 0.38
FOLD_PAIRED_LATE_WEAK = 0.30

# ── Preflop Thresholds ────────────────────────────────────────────────────────
# SB open
SB_OPEN_THRESHOLD = 0.46
SB_OPEN_MATCH_ADJ = 0.02
SB_LIMP_THRESHOLD = 0.36

# BB vs limp (iso raise)
BB_ISO_THRESHOLD = 0.57
BB_VPIP_FOLD_ADJUST_SCALE = 0.08
BB_FTR_FOLD_ADJUST_SCALE = 0.05

# BB vs raise
BB_VALUE_3BET_THRESHOLD = 0.60
BB_BLUFF_3BET_LOW = 0.38
BB_BLUFF_3BET_HIGH = 0.54
BB_BLUFF_3BET_FREQ = 0.25
BB_CALL_THRESHOLD = 0.37

# SB vs reraise
SB_PREMIUM_4BET_THRESHOLD = 0.78
SB_FACING_ALLIN_CALL = 0.55
SB_VS_RERAISE_CALL = 0.55
SB_VS_RERAISE_POT_SLACK = 0.03

# Light 4-bet
LIGHT_4BET_MIN_CONFIDENCE = 0.15
LIGHT_4BET_MIN_OPP_PFR = 0.25
LIGHT_4BET_MAX_OPP_4BET = 0.10
LIGHT_4BET_STRENGTH_LOW = 0.30
LIGHT_4BET_STRENGTH_HIGH = 0.55
LIGHT_4BET_FREQ_ROLL_CAP = 0.60
LIGHT_4BET_SIZE_MULT = 2.5
LIGHT_4BET_STACK_CAP = 0.25
LIGHT_4BET_HALF_STACK_CAP = 0.50

# Trash hand detection
TRASH_STRENGTH_THRESHOLD = 0.30

# ── Tournament Pressure ───────────────────────────────────────────────────────
# match_pressure_profile
LATE_HANDS_THRESHOLD = 12
LATE_HANDS_SCALE = 10.0
CHASE_BB_SCALE = 3.5
CHASE_BB_OFFSET = 0.8
PROTECT_BB_SCALE = 3.0
PROTECT_BB_OFFSET = 0.8
CHASE_DESPERATE_HANDS = 8
CHASE_DESPERATE_BB = 8
CHASE_MAX_NORMAL = 0.25

PROTECT_THRESHOLD_DELTA = 0.055
CHASE_THRESHOLD_DELTA = 0.055
PROTECT_SIZING_DELTA = -0.10
CHASE_SIZING_DELTA = 0.16
PROTECT_OPEN_DELTA = 0.020
CHASE_OPEN_DELTA = -0.030
PROTECT_BLUFF_DELTA = -0.08
CHASE_BLUFF_DELTA = 0.10

# apply_anti_lock_pressure overrides
ANTI_LOCK_CHASE = 0.90
ANTI_LOCK_THRESHOLD = -0.075
ANTI_LOCK_SIZING = 0.18
ANTI_LOCK_OPEN = -0.045
ANTI_LOCK_BLUFF = 0.13

# ── Draw Quality ──────────────────────────────────────────────────────────────
# Flush draw quality
FLUSH_DRAW_NUT = 0.21
FLUSH_DRAW_NON_NUT = 0.16
FLUSH_DRAW_NEAR_NUT = 0.185
FLUSH_DRAW_HIGH = 0.170
FLUSH_DRAW_LOW_PENALTY = -0.025
FLUSH_DRAW_PAIRED_PENALTY = -0.020

# Straight draw quality
STRAIGHT_DRAW_OPEN_ENDED = 0.17
STRAIGHT_DRAW_GUTSHOT = 0.09  # used in straight_draw_value; draw_profile uses 0.10
STRAIGHT_DRAW_DOUBLE_GUTSHOT = 0.13

# Combo draw bonus
COMBO_DRAW_BONUS = 0.04

# Overcard bonuses
OVERCARD_FLOP_BONUS = 0.025
OVERCARD_MULTI_BONUS = 0.015

# Draw quality caps
DRAW_QUALITY_CAP = 0.35
DRAW_SEMI_BLUFF_BASE = 0.16
DRAW_SEMI_BLUFF_GUTSHOT_OVERCARD = 0.13

# ── Simulation Range Weights ──────────────────────────────────────────────────
SIMULATIONS_BY_PUBLIC_COUNT = {
    0: 500,
    3: 700,
    4: 900,
    5: 0,
}
EXTRA_SIMULATIONS_BY_PUBLIC_COUNT = {
    0: 200,
    3: 220,
    4: 180,
}

# Critical spot thresholds for extra simulation
CRITICAL_SPOT_RATIO = 0.25
CRITICAL_SPOT_BB_MULT = 4

# Range weight formula
RANGE_BASE_WEIGHT = 0.15
RANGE_POSTFLOP_FLOOR = 0.16
RANGE_MIN_WEIGHT = 1e-6

# ── Pot Odds / SPR ────────────────────────────────────────────────────────────
# Jam call buffer
JAM_BASE_BUFFER = 0.02
JAM_STRONG_SCALE = 0.2
JAM_STRONG_OFFSET = 0.65
JAM_THIN_BONUS = 0.04
JAM_MATCH_PROTECT_SCALE = 0.04
JAM_BUFFER_CAP = 0.14
JAM_ANTI_LOCK_PENALTY = -0.10

# Shove call buffer (when to_call >= my_chips)
SHOVE_BASE_BUFFER = 0.01
SHOVE_STRONG_OFFSET = 0.64

# Preflop call margin
PREFLOP_CALL_BASE = 0.005
PREFLOP_CALL_OOP_BONUS = 0.010
PREFLOP_CALL_TRASH_BONUS = 0.015
PREFLOP_TRASH_STRENGTH = 0.40

# Action threshold tiers by street
STRONG_THRESHOLD = [0.69, 0.65, 0.61, 0.59]
MEDIUM_THRESHOLD = [0.54, 0.50, 0.48, 0.48]
THRESHOLD_POS_IP_STRONG = -0.015
THRESHOLD_POS_IP_MEDIUM = -0.010
THRESHOLD_POS_OOP_STRONG = 0.020
THRESHOLD_POS_OOP_MEDIUM = 0.015
THRESHOLD_PREMIUM_STRONG = -0.03
THRESHOLD_PREMIUM_MEDIUM = -0.02
THRESHOLD_PREMIUM_FLOOR = 0.72
THRESHOLD_WEAK_STRONG = 0.04
THRESHOLD_WEAK_MEDIUM = 0.03
THRESHOLD_WEAK_FLOOR = 0.40

# Bluff / semi-bluff thresholds
RAISE_FOLD_THRESHOLD = 0.56
BLOCKER_RAISE_THRESHOLD = 0.55
BLUFF_DELTA_RAISE_SCALE = 0.30
BLUFF_DELTA_BLOCKER_SCALE = 0.32
DRAW_EQUITY_SLACK_PREMIUM = 0.05
DRAW_EQUITY_SLACK_NORMAL = 0.03
SEMI_BLUFF_MIN_DRAW = 0.12
SEMI_BLUFF_MIN_CONFIDENCE = 0.25

# Nutted risk coefficients
NUTTED_RISK_STRONG_MULT = 0.45
NUTTED_RISK_MEDIUM_MULT = 0.30
NUTTED_RISK_CALL_MULT = 0.50

# Check-raise trap
TRAP_MIN_CONFIDENCE = 0.15
TRAP_MIN_AGGR = 0.35
TRAP_MAX_WETNESS = 0.25
TRAP_FREQ_CAP = 25  # percent

# Trap nut slowplay
TRAP_NUT_MAX_POT = 1400

# Big pot threshold
BIG_POT_BASE = 1500
BIG_POT_PROTECT_SCALE = 350
BIG_POT_CHASE_SCALE = 250
BIG_POT_FLOOR = 1100
BIG_POT_CEIL = 1800
